name: My first workflow

on: push

jobs: 
    FirstJob:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first Github action!"
            - name: List files
              run: ls
            - name: Read file
              run: cat README.md