name: My first workflow

on: push

jobs: 
    FirstJob:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Listing Files
              run: |
                  echo "My first Github action!"
                  ls -ltra
                  cat README.md
                  
            # - name: List files
            #   run: ls
            # - name: Read file
            #   run: cat README.md